- name: General | Check if Nginx is already installed
  stat: path=/etc/init.d/nginx
  register: nginx_installed

- name: General | Install PHP Nginx packages
  apt: "name={{ item }} state=present"
  with_items:
    - php5
    - nginx
    - php5-fpm
    - php5-mysql
    - php-apc
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - php5-curl
    - php5-imap
    - sendmail
    - unzip
  when: nginx_installed.stat.exists == false

# - name: Apache | Enable php modules
#   apache2_module: "name={{ item }} state=present"
#   with_items:
#     - php5
#     - proxy
#     - proxy_http
#     - headers
#     - rewrite
#     - dir

- name: Nginx | Remove default site
  file:
   path: "{{ item }}"
   state: absent
  with_items:
    - /etc/nginx/sites-enabled/default.conf
    - /etc/nginx/sites-enabled/default

# - name: Apache | Apache environment variables file /etc/apache2/envvars
#   template:
#     src: apache-envvars
#     dest: /etc/apache2/envvars
#     owner: root
#     mode: 0644
#   tags:
#     - configuration

# - name: Apache | Prefork Configuration files
#   template:
#     src: mods-available-mpm-prefork.conf
#     dest: /etc/apache2/mods-available/mpm_prefork.conf
#     owner: root
#     mode: 0755
#   tags:
#     - configuration

# - name: Apache | Worker Configuration files
#   template:
#     src: mods-available-mpm-worker.conf
#     dest: /etc/apache2/mods-available/mpm_worker.conf
#     owner: root
#     mode: 0755
#   tags:
#     - configuration
#
# - name: Apache | Enable Prefork and Worker mods
#   file:
#     src: "/etc/apache2/mods-available/{{ item }}"
#     dest: "/etc/apache2/mods-enabled/{{ item }}"
#     state: link
#   with_items:
#     - mpm_prefork.conf
#     - mpm_prefork.load
#
- name: Nginx FPM | PHP Configuration file /etc/php5/fpm/php.ini
  template:
    src: php.ini
    dest: /etc/php5/fpm/php.ini
    owner: root
    mode: 0755
  tags:
    - configuration

- name: Nginx | PHP HTTP Proxy file /etc/php5/fpm/http_proxy.php
  template:
    src: http_proxy.php
    dest: /etc/php5/fpm/http_proxy.php
    owner: root
    mode: 0755
  tags:
    - configuration

- name: Nginx | Enable PHP modules
  shell: "php5enmod {{ item }}"
  with_items:
    - imap

- include: ioncube.yml
